### ISSUE TITLE
Open-source checklist

### ISSUE THREAD

**Issue by ricklambrechts** [minvws/nl-rdo-openid-connect-php-laravel#17]
- [x] Update documentation
- [x] #24
- [x] Check license file(s) and correct if needed
- [x] [Code review by security team](https://github.com/minvws/nl-rdo-openid-connect-php-laravel/issues/26)
- [x] Readme check
  - [x] Readability (use of domain terminology)
  - [x] Make sure you can get (it working in an application)
- [x] External code quality review
- [x] Determine repository synchronisation scheme (change this one to public)
- [x] Get written approval 
  - [x] Product owner
  - [x] Management team (RDO specific: CTO)
- [x] Update GH Actions to not use org/repo secrets
- [x] Configure repo for public use
- [x] Celebrate 🎉
